In [13]:
import pandas as pd

In [14]:
data = pd.read_csv('C:/Users/user/Downloads/classification data/sample.csv')
print(data)
print(type(data))

       Name  Country   Age   Salary Purchased
0     James   France  44.0  72000.0        No
1       Tim    Spain  27.0  48000.0       Yes
2     Sarah  Germany  30.0  54000.0        No
3    Robert    Spain  38.0  61000.0        No
4      Emma  Germany  40.0      NaN       Yes
5  Jennifer   France  35.0  58000.0       Yes
6     Linda    Spain   NaN  52000.0        No
7    Thomas   France  48.0  79000.0       Yes
8       Ben  Germany  50.0  83000.0        No
9  Scarlett   France  37.0  67000.0       Yes
<class 'pandas.core.frame.DataFrame'>

In [15]:
data.index

RangeIndex(start=0, stop=10, step=1)

In [16]:
data.columns

Index(['Name', 'Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [17]:
type(data.values)

numpy.ndarray

In [19]:
data.iloc[2,3]

54000.0

In [21]:
data.iloc[4:6, 1:3]

   Country   Age
4  Germany  40.0
5   France  35.0

In [22]:
data = pd.read_csv('C:/Users/user/Downloads/classification data/sample.csv')
data

       Name  Country   Age   Salary Purchased
0     James   France  44.0  72000.0        No
1       Tim    Spain  27.0  48000.0       Yes
2     Sarah  Germany  30.0  54000.0        No
3    Robert    Spain  38.0  61000.0        No
4      Emma  Germany  40.0      NaN       Yes
5  Jennifer   France  35.0  58000.0       Yes
6     Linda    Spain   NaN  52000.0        No
7    Thomas   France  48.0  79000.0       Yes
8       Ben  Germany  50.0  83000.0        No
9  Scarlett   France  37.0  67000.0       Yes

In [28]:
X = data.iloc[:,-1].values
y = data.iloc[:,-1].values
print(X)
print(y)
print(type(X))
print(type(y))

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>